name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ development ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.EC2_USERNAME }}
          SSH_KEY: ${{ secrets.KEY }}
          SSH_HOST: ${{ secrets.EC2_HOSTNAME }}

      - name: deploy
        run: |
          cd herding-cats-backend &&
          ls
