name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ development ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:   
      - name: DEPLOY
        uses: appleboy/ssh-action@latest
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.KEY }}
          script: |
            cd herding-cats-back-end &&
            ssh -vT git@github.com &&
            git pull &&
            npm install &&
            npm run build
