name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ development ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User ec2-user
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            PasswordAuthentication no
          END
        env:
          SSH_USER: ec2-user
          SSH_KEY: ${{ secrets.KEY }}
          SSH_HOST: ${{ secrets.EC2_HOSTNAME }}

      - name: deploy
        run: ssh staging 'git clone git@github.com:CHAZTATS/herding-cats-back-end.git'
