name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ development ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:   
      - name: DEPLOY
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{secrets.EC2_HOSTNAME}} 
          user: ${{secrets.EC2_USERNAME}} 
          private_key: ${{secrets.KEY}} 
          command: |
            cd herding-cats-back-end &&
            git pull &&
            npm install &&
            npm run build
